name: Promote to Staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to deploy (e.g., v1.2.3)'
        required: true
        type: string

env:
  TERRAFORM_VERSION: '1.5.7'
  AWS_DEFAULT_REGION: 'eu-west-1'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Set Version in tfvars
        run: |
          cd environments/staging
          if [ -f terraform.tfvars ]; then
            sed -i "s/^image_tag.*/image_tag = \"${{ github.event.inputs.version }}\"/" terraform.tfvars
            sed -i "s/^version.*/version = \"${{ github.event.inputs.version }}\"/" terraform.tfvars
          else
            echo "image_tag = \"${{ github.event.inputs.version }}\"" >> terraform.tfvars
            echo "version = \"${{ github.event.inputs.version }}\"" >> terraform.tfvars
          fi

      - name: Terraform Init
        run: |
          cd environments/staging
          terraform init -input=false
        
      - name: Terraform Plan
        id: plan
        run: |
          cd environments/staging
          terraform plan -input=false -out=tfplan -var="image_tag=${{ github.event.inputs.version }}" -var="version=${{ github.event.inputs.version }}"
      
      - name: Terraform Apply
        run: |
          cd environments/staging
          terraform apply -input=false tfplan
          
      - name: Run Post-Deployment Tests
        run: |
          echo "Running smoke tests against staging environment..."
          # Placeholder for actual test commands
          # cd scripts
          # ./run_smoke_tests.sh --env=staging
          
      - name: Tag Deployment
        run: |
          git tag "staging-${{ github.event.inputs.version }}-$(date +%Y%m%d%H%M%S)"
          git push origin "staging-${{ github.event.inputs.version }}-$(date +%Y%m%d%H%M%S)"
          
      - name: Notify Slack on Success
        uses: slackapi/slack-github-action@v1.25.0
        if: success()
        with:
          payload: |
            {
              "text": "✅ Promoted version ${{ github.event.inputs.version }} to Staging",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Successfully promoted version ${{ github.event.inputs.version }} to Staging*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Version:*\n${{ github.event.inputs.version }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Deployed by:*\n${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
      - name: Notify Slack on Failure
        uses: slackapi/slack-github-action@v1.25.0
        if: failure()
        with:
          payload: |
            {
              "text": "❌ Failed to promote version ${{ github.event.inputs.version }} to Staging",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *Failed to promote version ${{ github.event.inputs.version }} to Staging*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Version:*\n${{ github.event.inputs.version }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Attempted by:*\n${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
